// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

package clonepublicfieldonly

//codegen:generated
func (v example) Clone() example {
	return example{
		f: v.f,
	}
}
