// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help
package alias

//codegen:generated
func (v A) Clone() A {
	return A{
		U: v.U.CloneFunc(
			func(v string) string {
				return v
			},
		),
		UM: func(v map[string]U) map[string]U {
			var out map[string]U

			if v != nil {
				out = make(map[string]U, len(v))
			}

			inner := out
			for k, v := range v {
				inner[k] = v.CloneFunc(
					func(v string) string {
						return v
					},
				)
			}
			out = inner

			return out
		}(v.UM),
	}
}
