// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

package errors

//codegen:generated
func (v includesError) Clone() includesError {
	return includesError{
		err: v.err,
		errs: func(src []error) []error {
			if src == nil {
				return nil
			}
			dst := make([]error, len(src), cap(src))
			copy(dst, src)
			return dst
		}(v.errs),
	}
}

//codegen:generated
func (v errs) Clone() errs {
	return func(src []error) []error {
		if src == nil {
			return nil
		}
		dst := make([]error, len(src), cap(src))
		copy(dst, src)
		return dst
	}(v)
}
