// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

package dependant

//codegen:generated
func (v Root) Clone() Root {
	return Root{
		A: v.A.Clone(),
	}
}

//codegen:generated
func (v A) Clone() A {
	return A{
		B: v.B.Clone(),
		C: v.C.Clone(),
	}
}

//codegen:generated
func (v B) Clone() B {
	return B{
		C: v.C.Clone(),
	}
}

//codegen:generated
func (v C) Clone() C {
	return C{
		C: v.C,
	}
}
