// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

package mathbig

import (
	"math/big"
)

//codegen:generated
func (v Big) Clone() Big {
	return Big{
		Int: func(v *big.Int) *big.Int {
			new := big.NewInt(0)
			new.Set(v)
			return new
		}(v.Int),
		Float: func(v *big.Float) *big.Float {
			new := big.NewFloat(0)
			new.Set(v)
			return new
		}(v.Float),
		Rat: func(v *big.Rat) *big.Rat {
			new := big.NewRat(0, 1)
			new.Set(v)
			return new
		}(v.Rat),
	}
}
