/*
Copyright © 2024 ngicks <yknt.bsl@gmail.com>
*/
package cmd

import (
	"context"
	"os"

	"github.com/spf13/cobra"
)

const generationNotice = "// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.\n"

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "codegen",
	Short: "A swiss army knife code generator implementation for my own. see subcommands.",
	Long: `A swiss army knife code generator implementation for my own. see subcommands.
Some commends have child commands`,
	SilenceUsage: true,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute(ctx context.Context) {
	err := rootCmd.ExecuteContext(ctx)
	if err != nil {
		os.Exit(1)
	}
}
