// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help
package paramcb

//codegen:generated
func (v A[T]) CloneFunc(cloneT func(T) T) A[T] {
	return A[T]{
		A: v.A.CloneFunc(
			func(v string) string {
				return v
			},
			cloneT,
		),
		B: v.B.CloneFunc(
			func(v []string) []string {
				out := make([]string, len(v))

				inner := out
				for k, v := range v {
					inner[k] = v
				}
				out = inner

				return out
			},
		),
		C: v.C.CloneFunc(
			func(v C[string]) C[string] {
				return v.CloneFunc(
					func(v string) string {
						return v
					},
				)
			},
			func(v []C[string]) []C[string] {
				out := make([]C[string], len(v))

				inner := out
				for k, v := range v {
					inner[k] = v.CloneFunc(
						func(v string) string {
							return v
						},
					)
				}
				out = inner

				return out
			},
		),
	}
}

//codegen:generated
func (v B[T, U]) CloneFunc(cloneT func(T) T, cloneU func(U) U) B[T, U] {
	return B[T, U]{
		T: cloneT(v.T),
		U: cloneU(v.U),
	}
}

//codegen:generated
func (v C[T]) CloneFunc(cloneT func(T) T) C[T] {
	return C[T]{
		T: cloneT(v.T),
	}
}
