// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help
package simple

import (
	"maps"
	"slices"
)

//codegen:generated
func (v A) Clone() A {
	return A{
		A: v.A,
		B: v.B,
		C: func(v *int) *int {
			out := new(int)

			inner := out
			if v != nil {
				v := *v
				*inner = v
			}
			out = inner

			return out
		}(v.C),
	}
}

//codegen:generated
func (v B) Clone() B {
	return B{
		A: func(v []*[]string) []*[]string {
			out := make([]*[]string, len(v))

			inner := out
			for k, v := range v {
				outer := &inner
				inner := new([]string)
				if v != nil {
					v := *v
					*inner = slices.Clone(v)
				}
				(*outer)[k] = inner
			}
			out = inner

			return out
		}(v.A),
		B: maps.Clone(v.B),
		C: func(v []*map[int][3]string) []*map[int][3]string {
			out := make([]*map[int][3]string, len(v))

			inner := out
			for k, v := range v {
				outer := &inner
				inner := new(map[int][3]string)
				if v != nil {
					v := *v
					outer := &inner
					inner := make(map[int][3]string, len(v))
					for k, v := range v {
						inner[k] = v
					}
					(*outer) = &inner
				}
				(*outer)[k] = inner
			}
			out = inner

			return out
		}(v.C),
	}
}
