// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

//go:build linux || darwin

package constraint

//codegen:generated
func (v A) Clone() A {
	return A{
		A: v.A,
	}
}
