// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen plain --help
package patchtarget

import (
	sliceund "github.com/ngicks/und"
)

//undgen:generated
type NameOverlappingPlain struct {
	AHHH  int `und:"required"`
	OOOHH string
}

//undgen:generated
func (v NameOverlapping) UndPlain() NameOverlappingPlain {
	return NameOverlappingPlain{
		AHHH:  v.AHHH.Value(),
		OOOHH: v.OOOHH,
	}
}

//undgen:generated
func (v NameOverlappingPlain) UndRaw() NameOverlapping {
	return NameOverlapping{
		AHHH:  sliceund.Defined(v.AHHH),
		OOOHH: v.OOOHH,
	}
}
