// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help
package disalloweddependant

//codegen:generated
func (v B) Clone() B {
	return B{
		B: v.B,
	}
}
