// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help
package param

func (v Param[T, U]) CloneFunc(cloneT func(T) T, cloneU func(U) U) Param[T, U] {
	return Param[T, U]{}
}
