// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

package disallowedparam

import (
	"sync"
)

//codegen:generated
func (v A) Clone() A {
	return A{
		U: v.U.CloneFunc(
			func(v string) string {
				return v
			},
		),
		Ignored: v.Ignored.CloneFunc(
			func(v *sync.Mutex) *sync.Mutex {
				return v
			},
		),
	}
}
