// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen plain --help
package sub

import (
	"github.com/ngicks/go-codegen/codegen/undgen/internal/targettypes/sub2"
)

//undgen:generated
type IncludesImplementorPlain struct {
	Foo sub2.FooPlain[int]
}

//undgen:generated
func (v IncludesImplementor) UndPlain() IncludesImplementorPlain {
	return IncludesImplementorPlain{
		Foo: v.Foo.UndPlain(),
	}
}

//undgen:generated
func (v IncludesImplementorPlain) UndRaw() IncludesImplementor {
	return IncludesImplementor{
		Foo: v.Foo.UndRaw(),
	}
}
