// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help
package simpleasm

//codegen:generated
func (v A) Clone() A {
	return func(v [5][]map[string]*[][]string) [5][]map[string]*[][]string {
		out := [5][]map[string]*[][]string{}

		inner := out
		for k, v := range v {
			outer := &inner
			inner := make([]map[string]*[][]string, len(v))
			for k, v := range v {
				outer := &inner
				inner := make(map[string]*[][]string, len(v))
				for k, v := range v {
					outer := &inner
					inner := new([][]string)
					if v != nil {
						v := *v
						outer := &inner
						inner := make([][]string, len(v))
						for k, v := range v {
							outer := &inner
							inner := make([]string, len(v))
							for k, v := range v {
								inner[k] = v
							}
							(*outer)[k] = inner
						}
						(*outer) = &inner
					}
					(*outer)[k] = inner
				}
				(*outer)[k] = inner
			}
			(*outer)[k] = inner
		}
		out = inner

		return out
	}(v)
}
