// Code generated by github.com/ngicks/go-codegen/codegen DO NOT EDIT.
// to regenerate the code, refer to help by invoking
// go run github.com/ngicks/go-codegen/codegen cloner --help

package any

//codegen:generated
func (v Any) Clone() Any {
	return Any{
		A: v.A,
	}
}
