package testtargets

//go:generate go run ../../../ undgen plain -v --pkg ./...
//go:generate go run ../../../ undgen validator -v --pkg ./...
//go:generate go run ../../../ undgen patch -v --pkg ./deeplynested ...
